# Default configuration for ComfyWatchman
# This file is loaded automatically if present in the config/ directory.
# Environment variables can override these values.

# Paths
comfyui_root = "/home/coldaine/StableDiffusionWorkflow/ComfyUI-stable"
workflow_dirs = [
    "/home/coldaine/StableDiffusionWorkflow/ComfyUI-stable/user/default/workflows"
]
output_dir = "output"
log_dir = "log"
search_log_file = "qwen_search_history.log"
download_counter_file = "download_counter.txt"

# Note: state_dir is now accessed via state.json_path (see State Management section below)

# API Settings
civitai_api_base = "https://civitai.com/api/v1"
civitai_download_base = "https://civitai.com/api/download/models"
civitai_api_timeout = 30

# Model Settings
model_extensions = [
    ".safetensors",
    ".ckpt",
    ".pt",
    ".bin",
    ".pth"
]
model_type_mapping = { "CheckpointLoaderSimple" = "checkpoints", "CheckpointLoader" = "checkpoints", "LoraLoader" = "loras", "LoraLoaderModelOnly" = "loras", "VAELoader" = "vae", "CLIPLoader" = "clip", "DualCLIPLoader" = "clip", "ControlNetLoader" = "controlnet", "UpscaleModelLoader" = "upscale_models", "CLIPVisionLoader" = "clip_vision", "UNETLoader" = "unet", "SAMLoader" = "sams", "GroundingDinoModelLoader" = "grounding-dino" }

# State Management
state_file = "download_state.json"

# Logging
log_format = "%Y-%m-%d %H:%M:%S"
run_id_format = "%Y%m%d_%H%M%S"

# Validation Thresholds
min_model_size = 1000000
recent_attempt_hours = 1
